matrix:
  include:
    - language: java
      jdk: oraclejdk8
      cache:
        directories:
        - $HOME/.m2
    - language: node_js
      node_js:
        - 9
      before_script: cd Secret-agency-web/src/main/react/secret-agency
      script: npm cache verify && npm install && npm run build && npm run test